---

name: Deploy Scomp

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-scomp: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: npm install aws-sdk
        run: npm install aws-sdk

      - name: sync to s3
        run: |+
          aws s3 sync . s3://yj-scomp.starwarsccg.org/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json --exclude create_json.js --exclude s3_website.yml
          aws cloudfront create-invalidation --distribution-id Z3MH6UOA83LQC4 --paths "/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



